### ISSUE TITLE
Filter quickstart -> archetype to avoid to include the travis file

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/platform#5]
Every quickstart contains a trigger-build.sh script (https://github.com/obsidian-toaster-quickstarts/quick_rest_springboot-tomcat/blob/master/trigger-build.sh)

- [x] Can we filter it to avoid that the maven archetype generated include it ?
- [ ] Can we manage such trigger build usign a webhook to avoid that the script appears too within the quickstarts ?

**Comment by gastaldi** [comment]
The ArchetypeBuilder needs to be updated for better extensibility. 
PR: https://github.com/fabric8io/ipaas-quickstarts/pull/1473

**Comment by gastaldi** [comment]
Fixed in https://github.com/obsidian-toaster/platform/commit/0c9d87654bd54308f1fcfaef298f882b62a101b8
